version: '3'

services:
  reactapp:
    build: app/
    image: reactapp:test
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpw
      MYSQL_DATABASE: wp_blog
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"

  blog:
    depends_on:
      - db
    image: wordpress
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: supersecretpw
      WORDPRESS_DB_NAME: wp_blog

  home:
    depends_on:
      - db
    image: wordpress
    ports:
      - "8081:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: supersecretpw
      WORDPRESS_DB_NAME: wp_home

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    environment:
      NGINX_HOST: 172.18.0.1
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/default.d/:/etc/nginx/default.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  db_data:
