version: '3'

services:
  reactapp:
    build: app/
    image: reactapp:test
    networks:
      - frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000

  db:
    image: mysql:5.7
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpw
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  adminer:
    image: adminer
    networks:
      - backend
    restart: always
    ports:
      - "8081:8080"

  blog:
    depends_on:
      - db
    image: wordpress
    networks:
      - frontend
      - backend
    volumes:
      - ./wordpress/wp-cli.phar:/usr/local/bin/wp-cli
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_INSTALL_TYPE: "multisite"
      WORDPRESS_SITE_URL: "http://localhost/blog"
  
  nginx:
    image: nginx:latest
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    environment:
      NGINX_HOST: nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/default.d/:/etc/nginx/default.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  db_data:

networks:
  frontend:
  backend:
