version: '3'

services:
  db:
    image: mysql:5.7
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: supersecretpw
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/blog.conf:/etc/nginx/default.conf/

volumes:
  db_data:

